export const allActivityData = [
    {
        id: "today-divider",
        avatar: "",
        name: "",
        action: "",
        time: "",
        initials: "",
        section: "Today",
    },
    {
        id: "1",
        avatar: "/professional-man.png",
        name: "Neil Roberts",
        action: "has successfully booked new flights for his upcoming trip.",
        time: "12:34 AM",
        initials: "NR",
    },
    {
        id: "2",
        avatar: "/professional-woman-diverse.png",
        name: "Emma Johnson",
        action: "has successfully booked new flights for her upcoming vacation",
        time: "11:30 AM",
        initials: "EJ",
    },
    {
        id: "3",
        avatar: "/diverse-business-person.png",
        name: "Tracks Invoice",
        action: "actions: creation, edits, sends, and payment status",
        time: "11:16 AM",
        initials: "TI",
    },
    {
        id: "4",
        avatar: "/professional-person.png",
        name: "Tracks Invoice",
        action: "actions: creation, edits, sends, and payment status",
        time: "11:16 AM",
        initials: "TI",
    },
    {
        id: "5",
        avatar: "/diverse-team-manager.png",
        name: "Logs",
        action: "creation, deletion, updates, and permission changes of users",
        time: "11:00 AM",
        initials: "L",
    },
    {
        id: "6",
        avatar: "/accountant-desk.png",
        name: "Tracks Invoice",
        action: "actions: creation, edits, sends, and payment status",
        time: "11:00 AM",
        initials: "TI",
    },
    {
        id: "yesterday-divider",
        avatar: "",
        name: "",
        action: "",
        time: "",
        initials: "",
        section: "Yesterday",
    },
    {
        id: "7",
        avatar: "/professional-man.png",
        name: "Neil Roberts",
        action: "has successfully booked new flights for his upcoming trip.",
        time: "11:30 AM",
        initials: "NR",
    },
    {
        id: "8",
        avatar: "/professional-woman-diverse.png",
        name: "Emma Johnson",
        action: "has successfully booked new flights for her upcoming vacation",
        time: "11:30 AM",
        initials: "EJ",
    },
    {
        id: "9",
        avatar: "/diverse-business-person.png",
        name: "Tracks Invoice",
        action: "actions: creation, edits, sends, and payment status",
        time: "11:00 AM",
        initials: "TI",
    },
    {
        id: "10",
        avatar: "/accountant-desk.png",
        name: "Tracks Invoice",
        action: "actions: creation, edits, sends, and payment status",
        time: "11:00 AM",
        initials: "TI",
    },
];
export const departmentManagerData = [
    {
        departmentName: "Traveler",
        assignedUsers: "20",
        managers: [
            "https://randomuser.me/api/portraits/men/34.jpg",
            "https://randomuser.me/api/portraits/men/35.jpg",
            "https://randomuser.me/api/portraits/men/36.jpg",
            "https://randomuser.me/api/portraits/men/37.jpg",
            "https://randomuser.me/api/portraits/men/38.jpg",
        ],
        activation: true,
    },
    {
        departmentName: "Service Provider",
        assignedUsers: "20",
        managers: [
            "https://randomuser.me/api/portraits/men/39.jpg",
            "https://randomuser.me/api/portraits/men/40.jpg",
            "https://randomuser.me/api/portraits/men/41.jpg",
        ],
        activation: false,
    },
    {
        departmentName: "Account",
        assignedUsers: "20",
        managers: [
            "https://randomuser.me/api/portraits/men/42.jpg",
            "https://randomuser.me/api/portraits/men/43.jpg",
        ],
        activation: true,
    },
    {
        departmentName: "Marketing",
        assignedUsers: "20",
        managers: [
            "https://randomuser.me/api/portraits/men/44.jpg",
            "https://randomuser.me/api/portraits/men/45.jpg",
        ],
        activation: true,
    },
    {
        departmentName: "Service Provider",
        assignedUsers: "20",
        managers: [
            "https://randomuser.me/api/portraits/men/46.jpg",
            "https://randomuser.me/api/portraits/men/47.jpg",
        ],
        activation: false,
    },
    {
        departmentName: "Service Provider",
        assignedUsers: "20",
        managers: [
            "https://randomuser.me/api/portraits/men/48.jpg",
            "https://randomuser.me/api/portraits/men/49.jpg",
            "https://randomuser.me/api/portraits/men/50.jpg",
        ],
        activation: true,
    },
    {
        departmentName: "Service Provider",
        assignedUsers: "20",
        managers: [
            "https://randomuser.me/api/portraits/men/51.jpg",
            "https://randomuser.me/api/portraits/men/52.jpg",
            "https://randomuser.me/api/portraits/men/53.jpg",
        ],
        activation: true,
    },
];
export const officeLocationsData = [
    {
        officeName: "ABC, Branch 02",
        address: "2118 Thornridge Cir. Syracuse, Connecticut 35624",
        managers: [
            "https://randomuser.me/api/portraits/men/34.jpg",
            "https://randomuser.me/api/portraits/men/35.jpg",
            "https://randomuser.me/api/portraits/men/36.jpg",
            "https://randomuser.me/api/portraits/men/37.jpg",
            "https://randomuser.me/api/portraits/men/38.jpg",
        ],
        activation: true,
        numberOfUsers: 22,
    },
    {
        officeName: "IKEA, HQ Branch",
        address: "3891 Ranchview Dr. Richardson, California 62639",
        managers: [
            "https://randomuser.me/api/portraits/men/39.jpg",
            "https://randomuser.me/api/portraits/men/40.jpg",
            "https://randomuser.me/api/portraits/men/41.jpg",
        ],
        activation: false,
        numberOfUsers: 24,
    },
    {
        officeName: "ABC, Branch 04",
        address: "6391 Elgin St. Celina, Delaware 10299",
        managers: [
            "https://randomuser.me/api/portraits/men/42.jpg",
            "https://randomuser.me/api/portraits/men/43.jpg",
        ],
        activation: true,
        numberOfUsers: 21,
    },
    {
        officeName: "ABC, Branch 04",
        address: "2118 Thornridge Cir. Syracuse, Connecticut 35624",
        managers: [
            "https://randomuser.me/api/portraits/men/44.jpg",
            "https://randomuser.me/api/portraits/men/45.jpg",
        ],
        activation: true,
        numberOfUsers: 11,
    },
    {
        officeName: "ABC, Branch 04",
        address: "6391 Elgin St. Celina, Delaware 10299 ",
        managers: [
            "https://randomuser.me/api/portraits/men/46.jpg",
            "https://randomuser.me/api/portraits/men/47.jpg",
        ],
        activation: false,
        numberOfUsers: 2,
    },
    {
        officeName: "ABC, Branch 04",
        address: "3891 Ranchview Dr. Richardson, California 62639",
        managers: [
            "https://randomuser.me/api/portraits/men/48.jpg",
            "https://randomuser.me/api/portraits/men/49.jpg",
            "https://randomuser.me/api/portraits/men/50.jpg",
        ],
        activation: true,
        numberOfUsers: 1,
    },
    {
        officeName: "ABC, Branch 04",
        address: "2118 Thornridge Cir. Syracuse, Connecticut 35624",
        managers: [
            "https://randomuser.me/api/portraits/men/51.jpg",
            "https://randomuser.me/api/portraits/men/52.jpg",
            "https://randomuser.me/api/portraits/men/53.jpg",
        ],
        activation: true,
        numberOfUsers: 21,
    },
];
export const customFieldManageData = [
    {
        for: "Travel Request",
        name: "Id Number",
        type: "number",
        options: "0",
        isRequired: true,
    },
    {
        for: "Trip Creation",
        name: "Department",
        type: "select",
        options: "7",
        isRequired: false,
    },
    {
        for: "User Profile",
        name: "Official name",
        type: "text",
        options: "7",
        isRequired: false,
    },
    {
        for: "Travel Request",
        name: "Official name",
        type: "text",
        options: "7",
        isRequired: true,
    },
    {
        for: "Trip Creation",
        name: "Official name",
        type: "text",
        options: "7",
        isRequired: true,
    },
    {
        for: "User Profile",
        name: "Official name",
        type: "text",
        options: "7",
        isRequired: false,
    },
    {
        for: "Travel Request",
        name: "Official name",
        type: "text",
        options: "7",
        isRequired: true,
    },
    {
        for: "Trip Creation",
        name: "Official name",
        type: "text",
        options: "7",
        isRequired: false,
    },
]
export const userRoleData = [
    {
        id: "#RID-01",
        roleName: "Admin",
        permissionsSummary: "20",
        roleType: "System",
        numberOfUsers: 21,
        details: "Company administrator with company-level permissions",
    },
    {
        id: "#RID-02",
        roleName: "Traveler",
        permissionsSummary: "20",
        roleType: "System",
        numberOfUsers: 23,
        details: "Company manager with team travel management permissions",
    },
    {
        id: "#RID-03",
        roleName: "Traveler",
        isManager: true,
        permissionsSummary: "20",
        roleType: "Company",
        numberOfUsers: 20,
        details: "Updated role with selected permissions",
    },
    {
        id: "#RID-04",
        roleName: "Traveler",
        permissionsSummary: "20",
        roleType: "Company",
        numberOfUsers: 25,
        details: "Updated role with selected permissions",
    },
    {
        id: "#RID-05",
        roleName: "Traveler",
        permissionsSummary: "20",
        roleType: "Company",
        numberOfUsers: 20,
        details: "Updated role with selected permissions",
    },
];
export const companyListForManageData = [
    {
        id: "COMID-01",
        companyName: "Gillette",
        website: "gillette.com",
        country: "Poland",
        contactPerson: {
            name: "Emily Johnson",
            email: "emily.johnson@techcorp.com",
            avatar: "https://randomuser.me/api/portraits/men/42.jpg",
        },
        totalUsers: 35,
        status: "Active",
    },
    {
        id: "COMID-02",
        companyName: "Louis Vuitton",
        website: "louisvuitton.com",
        country: "Viet Nam",
        contactPerson: {
            name: "Michael Brown",
            email: "michael.brown@techcorp.com",
            avatar: "https://randomuser.me/api/portraits/men/24.jpg",
        },
        totalUsers: 22,
        status: "Inactive",
    },
    {
        id: "COMID-03",
        companyName: "L'Oréal",
        website: "loreal.com",
        country: "Haiti",
        contactPerson: {
            name: "Sarah Davis",
            email: "sarah.davis@techcorp.com",
            avatar: "https://randomuser.me/api/portraits/men/22.jpg",
        },
        totalUsers: 35,
        status: "Pending",
    },
    {
        id: "COMID-04",
        companyName: "Nintendo",
        website: "nintendo.com",
        country: "Monaco",
        contactPerson: {
            name: "David Wilson",
            email: "david.wilson@techcorp.com",
            avatar: "https://randomuser.me/api/portraits/men/21.jpg",
        },
        totalUsers: 20,
        status: "Approved",
    },
    {
        id: "COMID-05",
        companyName: "Mitsubishi",
        website: "mitsubishi.com",
        country: "Monaco",
        contactPerson: {
            name: "Jessica Miller",
            email: "jessica.miller@techcorp.com",
            avatar: "https://randomuser.me/api/portraits/men/62.jpg",
        },
        totalUsers: 14,
        status: "Active",
    },
    {
        id: "COMID-06",
        companyName: "Gillette",
        website: "gillette.com",
        country: "Viet Nam",
        contactPerson: {
            name: "Robert Taylor",
            email: "robert.taylor@techcorp.com",
            avatar: "https://randomuser.me/api/portraits/men/25.jpg",
        },
        totalUsers: 16,
        status: "Active",
    },
    {
        id: "COMID-07",
        companyName: "Louis",
        website: "loreal.com",
        country: "Viet Nam",
        contactPerson: {
            name: "Lisa Anderson",
            email: "lisa.anderson@example.com",
            avatar: "https://randomuser.me/api/portraits/men/11.jpg",
        },
        totalUsers: 20,
        status: "Active",
    },
];
export const paymentMethodManageData = [
    {
        officeName: "John Smith",
        address: "12/25",
        department: "IT",
        costcenter: "CC001",
        region: "North",
        subsidiary: "Sub A",
        legalentity: "Entity 1",
        flights: "Yes",
        hotels: "Yes",
        trains: "No",
        cars: "Yes",
        guestInvite: "Available",
    },
];

export const employeeDataForManage = [
    {
        id: "U-00015",
        name: "John Doe",
        email: "john.doe@example.com",
        registered: true,
        department: "Marketing",
        status: true,
        companyOffice: "2372 Westheimer Rd, Santa Ana, Illinois 85486",
        title: "Marketing Manager",
        travelManager: "Jane Smith",
        delegates: "Mike Johnson",
        region: "North America",
        policyLevel: "Level 2",
        role: "Manager",
        permission: 10,
    },
    {
        id: "U-00045",
        name: "John Doe",
        email: "john.doe@example.com",
        registered: false,
        department: "Software Development",
        status: true,
        companyOffice: "2372 Westheimer Rd, Santa Ana, Illinois 85486",
        title: "Senior Developer",
        travelManager: "Sarah Wilson",
        delegates: "Tom Brown",
        region: "North America",
        policyLevel: "Level 3",
        role: "Developer",
        permission: 15,
    },
    {
        id: "U-00035",
        name: "John Doe",
        email: "john.doe@example.com",
        registered: true,
        department: "Quality Assurance",
        status: true,
        companyOffice: "2372 Westheimer Rd, Santa Ana, Illinois 85486",
        title: "QA Lead",
        travelManager: "Alex Davis",
        delegates: "Lisa Garcia",
        region: "North America",
        policyLevel: "Level 2",
        role: "Lead",
        permission: 20,
    },
    {
        id: "U-00065",
        name: "John Doe",
        email: "john.doe@example.com",
        registered: false,
        department: "DevOps",
        status: false,
        companyOffice: "2372 Westheimer Rd, Santa Ana, Illinois 85486",
        title: "DevOps Engineer",
        travelManager: "Chris Lee",
        delegates: "Pat Martinez",
        region: "North America",
        policyLevel: "Level 1",
        role: "Engineer",
        permission: 22,
    },
    {
        id: "U-00055",
        name: "John Doe",
        email: "john.doe@example.com",
        registered: true,
        department: "Marketing",
        status: true,
        companyOffice: "2372 Westheimer Rd, Santa Ana, Illinois 85486",
        title: "Marketing Specialist",
        travelManager: "Jane Smith",
        delegates: "Kevin White",
        region: "North America",
        policyLevel: "Level 1",
        role: "Specialist",
        permission: 20,
    },
];